"""Deprecated flat-module shim for ``kbutillib.kbase_catalog_client``.

AUTO-GENERATED by ``scripts/generate_deprecation_shims.py`` from
``LEGACY_MODULE_MAP`` in that script — do not hand-edit, regenerate instead.

The ``domains/`` reorg moved this module to ``kbutillib.domains.kbase.kbase_catalog_client``. This shim
exists only so that old ``from kbutillib.kbase_catalog_client import ...`` call sites keep
working (with a warning) instead of hard-failing with
``ModuleNotFoundError``. It re-exports the target module's public names via
a star-import, so the objects you get here are identical (``is``) to the
ones at the new location. Update your import to::

    from kbutillib.domains.kbase.kbase_catalog_client import ...

This shim is migration debt and is expected to be removed in a future
release.
"""

from __future__ import annotations

import warnings as _warnings

_warnings.warn(
    "kbutillib.kbase_catalog_client is deprecated; import from kbutillib.domains.kbase.kbase_catalog_client instead. "
    "This flat shim will be removed in a future release.",
    DeprecationWarning,
    stacklevel=2,
)

from kbutillib.domains.kbase.kbase_catalog_client import *  # noqa: E402,F401,F403
