"""Deprecated flat-module shim for ``kbutillib.ms_reconstruction_utils``.

AUTO-GENERATED by ``scripts/generate_deprecation_shims.py`` from
``LEGACY_MODULE_MAP`` in that script — do not hand-edit, regenerate instead.

The ``domains/`` reorg moved this module to ``kbutillib.domains.modeling.ms_reconstruction_utils``. This shim
exists only so that old ``from kbutillib.ms_reconstruction_utils import ...`` call sites keep
working (with a warning) instead of hard-failing with
``ModuleNotFoundError``. It re-exports the target module's public names via
a star-import, so the objects you get here are identical (``is``) to the
ones at the new location. Update your import to::

    from kbutillib.domains.modeling.ms_reconstruction_utils import ...

This shim is migration debt and is expected to be removed in a future
release.
"""

from __future__ import annotations

import warnings as _warnings

_warnings.warn(
    "kbutillib.ms_reconstruction_utils is deprecated; import from kbutillib.domains.modeling.ms_reconstruction_utils instead. "
    "This flat shim will be removed in a future release.",
    DeprecationWarning,
    stacklevel=2,
)

from kbutillib.domains.modeling.ms_reconstruction_utils import *  # noqa: E402,F401,F403
