repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: ruff
        name: ruff
        entry: ruff check
        args: [--fix]
        language: python
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [python, pyi]
