"""``kbu new-capability`` — stub generator for new @capability-decorated methods.

Writes three files (never overwriting existing ones):

1. **Method stub** — a Python module under ``src/kbutillib/domains/<domain>/``
   containing a class with one ``@capability``-decorated method stub.
2. **Pydantic schema stub** — an ``Input`` / ``Output`` pair in the same
   directory.
3. **Test stub** — ``tests/test_<domain>_<name>.py`` with a placeholder test.

The generator prints what it created and exits cleanly.  If *any* target file
already exists, it prints a warning and skips that file (never overwrites).
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

import click

# ---------------------------------------------------------------------------
# Template strings
# ---------------------------------------------------------------------------

_METHOD_STUB = '''\
"""``{domain}.{name}`` capability stub — generated by ``kbu new-capability``."""

from __future__ import annotations

from typing import Any

from kbutillib.core.capability import capability
from .schemas_{name} import {Name}Input, {Name}Output


class {ClassName}:
    """{Domain} utility stub for the ``{domain}.{name}`` capability."""

    @capability(
        domain="{domain}",
        summary="TODO: describe {domain}.{name}",
        tags=("{domain}", "{name}"),
        input_model={Name}Input,
        output_model={Name}Output,
        visibility="public",
    )
    def {name}(self, **kwargs: Any) -> Any:
        """TODO: implement {domain}.{name}.

        Parameters
        ----------
        **kwargs:
            Replace with real typed parameters once the method is designed.

        Returns
        -------
        Any
            Replace with a real return type.
        """
        raise NotImplementedError("{domain}.{name} is not yet implemented")
'''

_SCHEMA_STUB = '''\
"""Pydantic schemas for ``{domain}.{name}`` — generated by ``kbu new-capability``."""

from __future__ import annotations

from pydantic import BaseModel


class {Name}Input(BaseModel):
    """Input model for ``{domain}.{name}``.

    TODO: replace placeholder fields with real parameters.
    """

    placeholder: str = ""


class {Name}Output(BaseModel):
    """Output model for ``{domain}.{name}``."""

    result: object = None
'''

_TEST_STUB = '''\
"""Tests for ``{domain}.{name}`` — generated by ``kbu new-capability``."""

from __future__ import annotations

import pytest


class Test{Name}:
    """Placeholder tests for {domain}.{name}."""

    def test_not_implemented(self) -> None:
        """The stub raises NotImplementedError until implemented."""
        from kbutillib.domains.{domain}.{name}_impl import {ClassName}

        obj = {ClassName}()
        with pytest.raises(NotImplementedError):
            obj.{name}()

    def test_schemas_importable(self) -> None:
        """The schema stubs should be importable."""
        from kbutillib.domains.{domain}.schemas_{name} import (
            {Name}Input,
            {Name}Output,
        )

        _ = {Name}Input()
        _ = {Name}Output()
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _repo_root(start: Path) -> Optional[Path]:
    """Walk upward from *start* to find the repo root (contains pyproject.toml)."""
    for parent in [start, *start.parents]:
        if (parent / "pyproject.toml").exists():
            return parent
    return None


def _safe_write(path: Path, content: str, label: str) -> bool:
    """Write *content* to *path* safely.

    Returns ``True`` if written, ``False`` if skipped (existing file).
    Never overwrites an existing file.
    """
    if path.exists():
        click.echo(f"  SKIP (exists):  {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    click.echo(f"  CREATED ({label}): {path}")
    return True


# ---------------------------------------------------------------------------
# ``kbu new-capability`` command
# ---------------------------------------------------------------------------


@click.command(name="new-capability")
@click.argument("dotted_name")
@click.option(
    "--target-dir",
    default=None,
    type=click.Path(file_okay=False),
    help="Override the repo root (useful in tests).",
)
def new_capability_cmd(dotted_name: str, target_dir: Optional[str]) -> None:
    """Generate stub files for a new @capability-decorated method.

    DOTTED_NAME must be in the form ``<domain>.<name>``, e.g. ``demo.hello``.

    Creates (without overwriting):
    \b
      src/kbutillib/domains/<domain>/<name>_impl.py   — method stub
      src/kbutillib/domains/<domain>/schemas_<name>.py — pydantic schemas
      tests/test_<domain>_<name>.py                   — test stub

    All output goes to the repository root inferred from the current working
    directory, or to ``--target-dir`` if supplied.
    """
    # Parse dotted name
    parts = dotted_name.split(".")
    if len(parts) != 2 or not all(p.isidentifier() for p in parts):  # noqa: PIE801
        click.echo(
            f"Error: DOTTED_NAME must be <domain>.<name> with valid Python "
            f"identifiers, got {dotted_name!r}",
            err=True,
        )
        sys.exit(1)

    domain, name = parts
    Name = name.capitalize()  # noqa: N806
    ClassName = f"{domain.capitalize()}{name.capitalize()}Impl"  # noqa: N806
    Domain = domain.capitalize()  # noqa: N806

    # Locate repo root
    if target_dir:
        root = Path(target_dir).resolve()
    else:
        root = _repo_root(Path.cwd())
        if root is None:
            click.echo(
                "Error: could not locate repo root (no pyproject.toml found). "
                "Use --target-dir to specify the output root.",
                err=True,
            )
            sys.exit(1)

    click.echo(f"Generating stubs for capability: {dotted_name}")
    click.echo(f"  Root: {root}")

    # Template variables
    ctx = {
        "domain": domain,
        "name": name,
        "Name": Name,
        "ClassName": ClassName,
        "Domain": Domain,
    }

    # 1. Method stub
    method_path = root / "src" / "kbutillib" / "domains" / domain / f"{name}_impl.py"
    _safe_write(method_path, _METHOD_STUB.format(**ctx), "method stub")

    # 2. Schema stub
    schema_path = root / "src" / "kbutillib" / "domains" / domain / f"schemas_{name}.py"
    _safe_write(schema_path, _SCHEMA_STUB.format(**ctx), "schema stub")

    # 3. Test stub
    test_path = root / "tests" / f"test_{domain}_{name}.py"
    _safe_write(test_path, _TEST_STUB.format(**ctx), "test stub")

    click.echo("Done.")
