"""Backend protocol and result types for cheminformatics network expansion.

These definitions deliberately depend only on the Python standard library so
that importing :mod:`kbutillib.cheminformatics` never pulls in a heavy or
optional scientific dependency (RDKit, minedatabase, pandas). Concrete backends
import their dependencies lazily inside their own modules and report
``available == False`` with an explanatory ``unavailable_reason`` when a
dependency is missing -- importing the package must never raise.

The domain here is *in-silico reaction prediction / metabolic network
expansion*: given one or more seed compounds and a set of reaction rules
(SMARTS reaction operators), enumerate the reactions and product compounds that
the rules generate. Tools that implement this include Pickaxe (the
Tyo/Henry-lab ``minedatabase`` package) and rule sets such as RetroRules.

No backend ever fabricates a structure or a rule match. An expansion that
produces nothing returns an empty :class:`ExpansionResult` (with warnings),
never an invented reaction.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Protocol, runtime_checkable


class BackendUnavailableError(RuntimeError):
    """Raised when a cheminformatics backend is asked to compute but its
    dependency or external tool is not installed/configured.

    Callers that prefer graceful degradation should check
    :attr:`ExpansionBackend.available` first, or use
    :class:`kbutillib.network_expansion_utils.NetworkExpansionUtils`, which
    catches this and tries the next backend.
    """


@dataclass
class PredictedCompound:
    """A compound produced (or seeded) during a network expansion.

    ``smiles`` is the canonical SMILES as reported by the backend. ``None`` for
    any field means "not provided by this backend"; it is never a stand-in for a
    real value.
    """

    compound_id: str
    smiles: Optional[str] = None
    inchikey: Optional[str] = None
    formula: Optional[str] = None
    generation: Optional[int] = None
    is_seed: bool = False
    raw: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain JSON-serializable dict representation."""
        return {
            "compound_id": self.compound_id,
            "smiles": self.smiles,
            "inchikey": self.inchikey,
            "formula": self.formula,
            "generation": self.generation,
            "is_seed": self.is_seed,
        }


@dataclass
class PredictedReaction:
    """A single predicted reaction generated by applying a reaction operator.

    The reaction is expressed as compound ids referring to entries in the
    owning :class:`ExpansionResult`. ``smarts`` / ``smiles`` carry the rule and
    the reaction SMILES when the backend provides them.
    """

    reaction_id: str
    backend: str
    operator: Optional[str] = None
    reactant_ids: List[str] = field(default_factory=list)
    product_ids: List[str] = field(default_factory=list)
    reaction_smiles: Optional[str] = None
    rule_smarts: Optional[str] = None
    generation: Optional[int] = None
    warnings: List[str] = field(default_factory=list)
    raw: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain JSON-serializable dict representation."""
        return {
            "reaction_id": self.reaction_id,
            "backend": self.backend,
            "operator": self.operator,
            "reactant_ids": list(self.reactant_ids),
            "product_ids": list(self.product_ids),
            "reaction_smiles": self.reaction_smiles,
            "rule_smarts": self.rule_smarts,
            "generation": self.generation,
            "warnings": list(self.warnings),
        }


@dataclass
class ExpansionResult:
    """The full result of expanding a seed compound set with a rule set.

    ``compounds`` maps compound id -> :class:`PredictedCompound` (seeds plus all
    generated products). ``reactions`` is the list of predicted reactions. An
    expansion that produced nothing is an empty result with explanatory
    ``warnings`` -- never a fabricated reaction.
    """

    backend: str
    compounds: Dict[str, PredictedCompound] = field(default_factory=dict)
    reactions: List[PredictedReaction] = field(default_factory=list)
    generations: int = 0
    warnings: List[str] = field(default_factory=list)
    raw: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_expanded(self) -> bool:
        """True if at least one reaction was generated."""
        return len(self.reactions) > 0

    @property
    def n_compounds(self) -> int:
        """Number of compounds (seeds + products)."""
        return len(self.compounds)

    @property
    def n_reactions(self) -> int:
        """Number of predicted reactions."""
        return len(self.reactions)

    def product_compounds(self) -> List[PredictedCompound]:
        """Return only the non-seed (generated) compounds."""
        return [c for c in self.compounds.values() if not c.is_seed]

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain JSON-serializable dict representation."""
        return {
            "backend": self.backend,
            "generations": self.generations,
            "compounds": {cid: c.to_dict() for cid, c in self.compounds.items()},
            "reactions": [r.to_dict() for r in self.reactions],
            "warnings": list(self.warnings),
        }


@runtime_checkable
class ExpansionBackend(Protocol):
    """Structural interface every network-expansion backend implements.

    A backend is *optional*. Construction must never raise merely because the
    backend's dependency is missing; instead the backend reports
    :attr:`available` as ``False`` and explains via :attr:`unavailable_reason`.
    Compute methods raise :class:`BackendUnavailableError` if called while
    unavailable.
    """

    #: Short stable identifier, e.g. ``"pickaxe"``.
    name: str

    @property
    def available(self) -> bool:
        """Whether this backend can currently perform computations."""
        ...

    @property
    def unavailable_reason(self) -> Optional[str]:
        """Human-readable explanation when :attr:`available` is ``False``."""
        ...

    @property
    def capabilities(self) -> "frozenset[str]":
        """Set of capability tags this backend supports.

        Recognized tags: ``"expand"`` (enumerate a reaction network from
        seeds), ``"apply_rule"`` (apply a single SMARTS operator to a compound).
        """
        ...

    def expand(
        self,
        seed_smiles: Mapping[str, str],
        generations: int = 1,
        **kwargs: Any,
    ) -> ExpansionResult:
        """Expand a seed compound set into a reaction network.

        Args:
            seed_smiles: Mapping of compound id -> SMILES for the seed set.
            generations: Number of expansion rounds to perform.
            **kwargs: Backend-specific options (rule set selection, pruning,
                filters, output directory, etc.).

        Returns:
            An :class:`ExpansionResult`.

        Raises:
            BackendUnavailableError: If the backend is not available.
        """
        ...
