#!/usr/bin/env python3
"""Build a COG -> description dictionary (``cog_description_map.tsv``) from NCBI ``cog-20.def.tab``.

``cog-20.def.tab`` is a plain tab-delimited file, one row per COG, no
header line. Column 1 is the COG accession (e.g. ``COG0001``); column 3
is the COG's short functional name, which is what this script emits as
the description. (Columns 2, 4+ -- functional category letters, an
example gene/protein, pathway annotation -- are not needed here.)

DO NOT COMMIT THE OUTPUT
-------------------------
``cog_description_map.tsv`` is derived from NCBI's bulk COG database
release -- third-party bulk ontology data, not this repo's own content.
The generated table must never be committed; it is built once per
deployment, on the compute host, from a release the host already holds,
and lives outside git under the deployment's data root.
``cog_description_map*.tsv`` is listed in this repo's ``.gitignore`` for
exactly this reason -- a future contributor should not "helpfully" commit a
run of this script.

Usage
-----
    python3 -m kbutillib.domains.genome.annotation.build_cog_description_map \\
        --cog-def-tab /path/to/cog-20.def.tab \\
        --release-version 2020 \\
        --output /path/to/deployment/data/cog_description_map.tsv
"""

from __future__ import annotations

import argparse
import datetime
import logging
import sys
from collections.abc import Iterator
from pathlib import Path

logger = logging.getLogger(__name__)

# Column 3 (0-indexed: 2) of cog-20.def.tab carries the COG's short
# functional name -- the description this script emits.
_DESCRIPTION_COLUMN = 2
_MIN_COLUMNS = _DESCRIPTION_COLUMN + 1


def _iter_cog_rows(cog_def_tab_file: Path) -> Iterator[tuple[str, str]]:
    """Yield ``(cog_id, description)`` pairs from a ``cog-20.def.tab`` file.

    No header row is expected (matching the real NCBI release); blank
    lines are skipped. Rows with fewer than ``_MIN_COLUMNS`` tab-separated
    fields, or an empty id/description, are skipped rather than raising --
    a handful of malformed rows in an otherwise well-formed release is not
    the release-schema trap this module guards against (see
    :func:`build_description_map`).
    """
    with cog_def_tab_file.open(
        "r", encoding="utf-8", errors="replace", newline=None
    ) as fh:
        for raw_line in fh:
            line = raw_line.rstrip("\n").rstrip("\r")
            if not line.strip():
                continue
            cols = line.split("\t")
            if len(cols) < _MIN_COLUMNS:
                continue
            cog_id = cols[0].strip()
            description = cols[_DESCRIPTION_COLUMN].strip()
            if not cog_id or not description:
                continue
            yield cog_id, description


def build_description_map(cog_def_tab_file: Path) -> dict[str, str]:
    """Parse ``cog-20.def.tab`` into ``{cog_id: description}``.

    Raises:
        RuntimeError: If the file yields zero non-empty ``(cog_id,
            description)`` pairs, named as "tab-delimited (column 1 =
            COG id, column 3 = description)" so a caller can tell this
            apart from a missing-file degradation. A file with fewer than
            3 columns per row parses cleanly under a naive
            ``line.split("\\t")`` and silently yields nothing useful --
            exactly the trap this guard exists to catch.
    """
    rows = list(_iter_cog_rows(cog_def_tab_file))
    if not rows:
        raise RuntimeError(
            f"NCBI cog-20.def.tab file at {cog_def_tab_file} produced zero "
            "non-empty (cog_id, description) rows using the expected "
            "tab-delimited layout (column 1 = COG id, column 3 = "
            "description, no header row). A release with fewer than 3 "
            "tab-separated columns per row, or a different column order, "
            f"parses cleanly and matches nothing. Inspect the raw file at "
            f"{cog_def_tab_file} to confirm its column layout."
        )
    return dict(rows)


def write_table(
    output_path: Path,
    descriptions: dict[str, str],
    *,
    release_version: str,
    cog_def_tab_file: Path,
) -> None:
    """Write the two-column ``cog_id\\tdescription`` table with a provenance header."""
    generated = datetime.datetime.now(tz=datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write(
            "# cog_description_map.tsv -- generated by "
            "kbutillib.domains.genome.annotation.build_cog_description_map\n"
        )
        fh.write(f"# cog_def_tab_release: {release_version}\n")
        fh.write(f"# source_cog_def_tab_file: {cog_def_tab_file}\n")
        fh.write(f"# generated_utc: {generated}\n")
        fh.write(f"# row_count: {len(descriptions)}\n")
        fh.write("# NCBI COG-derived content -- do not commit this file.\n")
        fh.write("# cog_id\tdescription\n")
        for cog_id in sorted(descriptions):
            fh.write(f"{cog_id}\t{descriptions[cog_id]}\n")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build cog_description_map.tsv, a COG -> description table, "
            "from an NCBI cog-20.def.tab release, for OntologyDictionary. "
            "Run this once per deployment on the compute host; never "
            "commit its output (see module docstring)."
        )
    )
    parser.add_argument(
        "--cog-def-tab",
        type=Path,
        required=True,
        help="Path to an NCBI cog-20.def.tab release file (uncompressed).",
    )
    parser.add_argument(
        "--release-version",
        required=True,
        help=(
            "Release/date identifier to record in the output header (e.g. "
            "'2020'). Not reliably auto-detectable from file content, so "
            "it must be supplied explicitly."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output path for cog_description_map.tsv (outside git; deployment data root).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable debug logging.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    descriptions = build_description_map(args.cog_def_tab)
    logger.info("Parsed %d cog_description_map rows.", len(descriptions))

    write_table(
        args.output,
        descriptions,
        release_version=args.release_version,
        cog_def_tab_file=args.cog_def_tab,
    )
    logger.info("Wrote %s (%d rows).", args.output, len(descriptions))
    return 0


if __name__ == "__main__":
    sys.exit(main())
