"""Reusable template-and-venv helpers shared by ``kbu new-project`` and
``kbu bootstrap``.

Public API
----------
- copy_template_tree
- compute_file_hashes
- run_venvman_project
- create_plain_venv
- parse_virtual_env_from_activate
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

from .manifest import sha256_file


# ---------------------------------------------------------------------------
# Template copy with substitution
# ---------------------------------------------------------------------------


def copy_template_tree(
    template_root: Path,
    dest: Path,
    substitutions: dict[str, str],
) -> None:
    """Copy template tree from *template_root* to *dest* with variable substitution.

    Substitutes ``{{key}}`` in both file/directory names and file contents.
    """
    def _substitute(text: str) -> str:
        for key, value in substitutions.items():
            text = text.replace(f"{{{{{key}}}}}", value)
        return text

    for src_path in template_root.rglob("*"):
        # Compute relative path with substitution applied to each component
        rel = src_path.relative_to(template_root)
        rel_parts = [_substitute(part) for part in rel.parts]
        dest_path = dest / Path(*rel_parts)

        if src_path.is_dir():
            dest_path.mkdir(parents=True, exist_ok=True)
        else:
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            # Attempt text substitution; fall back to binary copy if decode fails
            try:
                content = src_path.read_text(encoding="utf-8")
                content = _substitute(content)
                dest_path.write_text(content, encoding="utf-8")
            except UnicodeDecodeError:
                shutil.copy2(str(src_path), str(dest_path))


# ---------------------------------------------------------------------------
# file_hashes computation
# ---------------------------------------------------------------------------


def compute_file_hashes(project_root: Path, tracked_dirs: list[str]) -> dict[str, str]:
    """Compute SHA-256 hashes for all tracked files in *project_root*.

    Returns a dict mapping relative path string (forward-slash) → ``sha256:<hex>``.
    """
    hashes: dict[str, str] = {}
    for rel_dir in tracked_dirs:
        d = project_root / rel_dir
        if not d.is_dir():
            continue
        for f in sorted(d.rglob("*")):
            if f.is_file():
                rel = f.relative_to(project_root)
                rel_str = rel.as_posix()
                hashes[rel_str] = f"sha256:{sha256_file(f)}"
    return hashes


# ---------------------------------------------------------------------------
# venv helpers
# ---------------------------------------------------------------------------


def parse_virtual_env_from_activate(activate_sh: Path) -> Optional[Path]:
    """Extract the VIRTUAL_ENV path from an activate.sh generated by venvman."""
    try:
        text = activate_sh.read_text(encoding="utf-8")
    except OSError:
        return None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("VIRTUAL_ENV="):
            value = stripped[len("VIRTUAL_ENV="):].strip().strip('"').strip("'")
            if value:
                return Path(value)
    return None


def run_venvman_project(project_name: str, project_root: Path) -> tuple[Optional[Path], str]:
    """Run venvman to create a per-project venv.

    Returns ``(venv_python_path, error_detail)``.
    """
    result = subprocess.run(
        [
            "venvman",
            "create",
            "--project",
            project_name,
            "--dir",
            str(project_root),
            "--python",
            "3.11",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        if not detail:
            detail = f"venvman exited with code {result.returncode}"
        return None, detail

    # Resolve venv python from activate.sh written by venvman
    activate_sh = project_root / "activate.sh"
    if activate_sh.exists():
        venv_dir = parse_virtual_env_from_activate(activate_sh)
        if venv_dir:
            candidate = venv_dir / "bin" / "python"
            if candidate.exists():
                return candidate, ""
    return None, "venvman succeeded but VIRTUAL_ENV could not be resolved from activate.sh"


def create_plain_venv(project_root: Path) -> Path:
    """Create a plain .venv in *project_root* and return the python path."""
    subprocess.run(
        [sys.executable, "-m", "venv", ".venv"],
        cwd=str(project_root),
        check=True,
    )
    return project_root / ".venv" / "bin" / "python"
