"""``kbu new-project`` — scaffold a new KBUtilLib student project.

Creates a project directory from the ``templates/student-project/`` tree,
sets up a per-project venv, editable-installs KBUtilLib, registers a
Jupyter kernel, writes ``kbu-project.toml``, and runs ``git init``.

v1 targets macOS only.  On non-macOS, prints the v1 message and exits 1
unless ``KBU_PLATFORM_OVERRIDE=force`` is set.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import click

from .manifest import (
    now_utc_iso,
    sha256_file,
    write_project_manifest,
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_V1_MACOS_ONLY_MESSAGE = (
    "v1 currently targets macOS. Linux/Windows support is planned for v2. "
    "To install KBUtilLib manually for now: "
    "`python -m venv .venv && source .venv/bin/activate && "
    "pip install -e <path-to-KBUtilLib>`. "
    "Then register a Jupyter kernel: "
    "`python -m ipykernel install --user --name=kbutillib`. "
    "You can use the tier-2 skills once "
    "`/path/to/KBUtilLib/.claude/` is on your Claude Code skill search path."
)

#: Tracked subdirectories (relative to project root) that are hashed for update.
_TRACKED_DIRS = [".claude/commands", ".vscode"]


# ---------------------------------------------------------------------------
# KBUtilLib root resolution
# ---------------------------------------------------------------------------


def _kbutillib_root() -> Path:
    """Return the absolute path to the KBUtilLib repo root.

    src/kbutillib/cli/new_project.py → src/kbutillib/cli → src/kbutillib → src → repo_root
    """
    this_file = Path(__file__).resolve()
    return this_file.parent.parent.parent.parent


# ---------------------------------------------------------------------------
# Platform check
# ---------------------------------------------------------------------------


def _is_macos_or_override() -> bool:
    """Return True if this is macOS or KBU_PLATFORM_OVERRIDE=force is set."""
    return sys.platform == "darwin" or os.environ.get("KBU_PLATFORM_OVERRIDE") == "force"


def _is_darwin() -> bool:
    """Return True if this is macOS."""
    return sys.platform == "darwin"


# ---------------------------------------------------------------------------
# git helpers
# ---------------------------------------------------------------------------


def _git_commit(repo_root: Path) -> str:
    """Return the current HEAD commit SHA in *repo_root*, or empty string."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except OSError:
        pass
    return ""


# ---------------------------------------------------------------------------
# Template copy with substitution
# ---------------------------------------------------------------------------


def _copy_template_tree(
    template_root: Path,
    dest: Path,
    substitutions: dict[str, str],
) -> None:
    """Copy template tree from *template_root* to *dest* with variable substitution.

    Substitutes ``{{key}}`` in both file/directory names and file contents.
    """
    def _substitute(text: str) -> str:
        for key, value in substitutions.items():
            text = text.replace(f"{{{{{key}}}}}", value)
        return text

    for src_path in template_root.rglob("*"):
        # Compute relative path with substitution applied to each component
        rel = src_path.relative_to(template_root)
        rel_parts = [_substitute(part) for part in rel.parts]
        dest_path = dest / Path(*rel_parts)

        if src_path.is_dir():
            dest_path.mkdir(parents=True, exist_ok=True)
        else:
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            # Attempt text substitution; fall back to binary copy if decode fails
            try:
                content = src_path.read_text(encoding="utf-8")
                content = _substitute(content)
                dest_path.write_text(content, encoding="utf-8")
            except UnicodeDecodeError:
                shutil.copy2(str(src_path), str(dest_path))


# ---------------------------------------------------------------------------
# venv helpers
# ---------------------------------------------------------------------------


def _parse_virtual_env_from_activate(activate_sh: Path) -> Optional[Path]:
    """Extract the VIRTUAL_ENV path from an activate.sh generated by venvman."""
    try:
        text = activate_sh.read_text(encoding="utf-8")
    except OSError:
        return None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("VIRTUAL_ENV="):
            value = stripped[len("VIRTUAL_ENV="):].strip().strip('"').strip("'")
            if value:
                return Path(value)
    return None


def _run_venvman_project(project_name: str, project_root: Path) -> tuple[Optional[Path], str]:
    """Run venvman to create a per-project venv.

    Returns ``(venv_python_path, error_detail)``.
    """
    result = subprocess.run(
        [
            "venvman",
            "create",
            "--project",
            project_name,
            "--dir",
            str(project_root),
            "--python",
            "3.11",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        if not detail:
            detail = f"venvman exited with code {result.returncode}"
        return None, detail

    # Resolve venv python from activate.sh written by venvman
    activate_sh = project_root / "activate.sh"
    if activate_sh.exists():
        venv_dir = _parse_virtual_env_from_activate(activate_sh)
        if venv_dir:
            candidate = venv_dir / "bin" / "python"
            if candidate.exists():
                return candidate, ""
    return None, "venvman succeeded but VIRTUAL_ENV could not be resolved from activate.sh"


def _create_plain_venv(project_root: Path) -> Path:
    """Create a plain .venv in *project_root* and return the python path."""
    subprocess.run(
        [sys.executable, "-m", "venv", ".venv"],
        cwd=str(project_root),
        check=True,
    )
    return project_root / ".venv" / "bin" / "python"


# ---------------------------------------------------------------------------
# file_hashes computation
# ---------------------------------------------------------------------------


def _compute_file_hashes(project_root: Path, tracked_dirs: list[str]) -> dict[str, str]:
    """Compute SHA-256 hashes for all tracked files in *project_root*.

    Returns a dict mapping relative path string (forward-slash) → ``sha256:<hex>``.
    """
    hashes: dict[str, str] = {}
    for rel_dir in tracked_dirs:
        d = project_root / rel_dir
        if not d.is_dir():
            continue
        for f in sorted(d.rglob("*")):
            if f.is_file():
                rel = f.relative_to(project_root)
                rel_str = rel.as_posix()
                hashes[rel_str] = f"sha256:{sha256_file(f)}"
    return hashes


# ---------------------------------------------------------------------------
# Core new_project logic
# ---------------------------------------------------------------------------


def new_project(  # noqa: C901 — orchestration function
    path: Path,
    name: str,
    author: str,
    affiliation: str,
    orcid: str,
    first_subproject: Optional[str] = None,
) -> None:
    """Scaffold a new KBUtilLib student project at *path*.

    Steps:
    1. Reject if *path* exists.
    2. Copy ``templates/student-project/`` tree with ``{{project_name}}`` substitution.
    3. Platform gate (macOS or KBU_PLATFORM_OVERRIDE=force).
    4. Create per-project venv (venvman or .venv fallback).
    5. pip install -e <KBUTILLIB_ROOT> in venv.
    6. Register Jupyter kernel.
    7. Write kbu-project.toml with [update.file_hashes].
    8. git init + initial commit.
    9. Create first_subproject if given.
    10. Print Cursor instructions.
    """
    if path.exists():
        click.echo(f"Error: path already exists: {path}", err=True)
        sys.exit(1)

    kbu_root = _kbutillib_root()
    template_src = kbu_root / "templates" / "student-project"

    # Create destination and copy template
    path.mkdir(parents=True)
    if template_src.is_dir():
        _copy_template_tree(template_src, path, {"project_name": name})

    # Platform gate — checked before venv creation
    if not _is_macos_or_override():
        click.echo(_V1_MACOS_ONLY_MESSAGE)
        sys.exit(1)

    # Determine venvman availability (non-Darwin with override → treat absent)
    use_venvman = _is_darwin() and shutil.which("venvman") is not None

    venv_python: Optional[Path]
    venv_manager: str

    if use_venvman:
        click.echo(f"Detected venvman — creating project venv for {name} ...")
        venv_python, venvman_err = _run_venvman_project(name, path)
        if venv_python is None:
            click.echo(
                f"Warning: venvman create failed ({venvman_err}) — falling back to python -m venv .venv",
                err=True,
            )
            venv_python = _create_plain_venv(path)
            venv_manager = ".venv"
        else:
            venv_manager = "venvman"
    else:
        click.echo("Creating .venv with python -m venv ...")
        venv_python = _create_plain_venv(path)
        venv_manager = ".venv"

    venv_python_str = str(venv_python)

    # pip install -e <KBUTILLIB_ROOT>
    click.echo(f"Installing KBUtilLib editable from {kbu_root} ...")
    subprocess.run(
        [venv_python_str, "-m", "pip", "install", "-e", str(kbu_root)],
        check=True,
    )

    # Register Jupyter kernel
    click.echo(f"Registering Jupyter kernel '{name}' ...")
    subprocess.run(
        [
            venv_python_str,
            "-m",
            "ipykernel",
            "install",
            "--user",
            f"--name={name}",
            f"--display-name={name} (kbu)",
        ],
        check=True,
    )

    # Compute file hashes for tracked dirs
    file_hashes = _compute_file_hashes(path, _TRACKED_DIRS)

    # Get source commit
    source_commit = _git_commit(kbu_root)
    now = now_utc_iso()

    # Write kbu-project.toml
    manifest: dict = {
        "project": {
            "name": name,
            "created_at": now,
            "authors": [
                {
                    "name": author,
                    "affiliation": affiliation,
                    "orcid": orcid,
                }
            ],
        },
        "kbutillib": {
            "source_path": str(kbu_root),
            "source_commit": source_commit,
        },
        "update": {
            "last_pulled_at": now,
            "last_pulled_commit": source_commit,
            "file_hashes": file_hashes,
        },
    }
    write_project_manifest(path, manifest)

    # git init + initial commit
    subprocess.run(["git", "init"], cwd=str(path), check=True)
    subprocess.run(["git", "add", "."], cwd=str(path), check=True)
    subprocess.run(
        ["git", "commit", "-m", "feat(kbu): initialize project via kbu new-project"],
        cwd=str(path),
        check=True,
    )

    # Create first subproject if given
    if first_subproject:
        click.echo(f"Creating first subproject '{first_subproject}' ...")
        subprocess.run(
            [venv_python_str, "-m", "kbutillib", "subproject", "create", first_subproject],
            cwd=str(path),
            check=False,  # best-effort; don't fail the whole new-project on this
        )

    # Print instructions
    workspace_file = f"{name}.code-workspace"
    click.echo(f"\nProject created at: {path}")
    click.echo(f"Open in Cursor: cursor {path}/{workspace_file}")
    click.echo("Then in Cursor: open terminal -> run claude -> type /kbu-start")


# ---------------------------------------------------------------------------
# Click command
# ---------------------------------------------------------------------------


@click.command("new-project")
@click.argument("path", type=click.Path(path_type=Path))
@click.option("--name", default=None, help="Project name.")
@click.option("--author", default=None, help="Author name.")
@click.option("--affiliation", default=None, help="Author affiliation.")
@click.option("--orcid", default=None, help="Author ORCID.")
@click.option("--first-subproject", default=None, help="Name of the first subproject to create.")
def new_project_command(
    path: Path,
    name: Optional[str],
    author: Optional[str],
    affiliation: Optional[str],
    orcid: Optional[str],
    first_subproject: Optional[str],
) -> None:
    """Scaffold a new KBUtilLib student project.

    PATH is the destination directory (must not exist).

    Prompts for any required arguments not provided via flags.
    """
    if name is None:
        name = click.prompt("Project name")
    if author is None:
        author = click.prompt("Author name")
    if affiliation is None:
        affiliation = click.prompt("Author affiliation")
    if orcid is None:
        orcid = click.prompt("Author ORCID")

    new_project(
        path=path,
        name=name,
        author=author,
        affiliation=affiliation,
        orcid=orcid,
        first_subproject=first_subproject,
    )
